/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ProseModePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var ProseModePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.PROSE_MODE_CLASS = "prose-mode";
    this.PROSE_PATH_PATTERN = /\/prose\//i;
  }
  async onload() {
    console.log("Loading Prose Mode plugin");
    this.app.workspace.onLayoutReady(() => {
      this.applyProseModeToActiveLeaf();
    });
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        this.applyProseModeToActiveLeaf();
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        this.applyProseModeToActiveLeaf();
      })
    );
  }
  onunload() {
    console.log("Unloading Prose Mode plugin");
    this.removeAllProseModeClasses();
  }
  applyProseModeToActiveLeaf() {
    this.removeAllProseModeClasses();
    const activeLeaf = this.app.workspace.activeLeaf;
    if (!activeLeaf)
      return;
    const file = this.app.workspace.getActiveFile();
    if (!file)
      return;
    if (this.isProsePath(file.path)) {
      this.addProseModeClass(activeLeaf);
    }
  }
  isProsePath(path) {
    return this.PROSE_PATH_PATTERN.test(path);
  }
  addProseModeClass(leaf) {
    var _a;
    const container = leaf.view.containerEl;
    if (container && !container.classList.contains(this.PROSE_MODE_CLASS)) {
      container.classList.add(this.PROSE_MODE_CLASS);
      console.log("Prose mode enabled for:", (_a = this.app.workspace.getActiveFile()) == null ? void 0 : _a.path);
    }
  }
  removeAllProseModeClasses() {
    document.querySelectorAll(`.${this.PROSE_MODE_CLASS}`).forEach((el) => {
      el.classList.remove(this.PROSE_MODE_CLASS);
    });
  }
};
